### Get all categories for all months
GET http://localhost:8000/api/categories
Authorization: Bearer {{auth}}

### Get categories for current month
GET http://localhost:8000/api/categories/current
Authorization: Bearer {{auth}}

### Get categories for specific month
GET http://localhost:8000/api/categories/2024-11
Authorization: Bearer {{auth}}

### Create new category
POST http://localhost:8000/api/categories
Authorization: Bearer {{auth}}
Content-Type: application/json
Accept: application/json

{
    "name": "New Category",
    "expected": 500.00,
    "budget_month": "2024-03-01"
}

### Update category
PUT http://localhost:8000/api/categories/1
Authorization: Bearer {{auth}}
Content-Type: application/json
Accept: application/json

{
    "name": "Updated Category",
    "expected": 600.00
}

### Delete category
DELETE http://localhost:8000/api/categories/1
Authorization: Bearer {{auth}}
Content-Type: application/json
Accept: application/json

### Income
GET http://localhost:8000/api/budgets/2024-11/paychecks
Authorization: Bearer {{auth}}
Content-Type: application/json
Accept: application/json

### Create income for a month
POST http://localhost:8000/api/income
Authorization: Bearer {{auth}}
Content-Type: application/json
Accept: application/json

{
    "budget_month": "2024-11",
    "expected_income": 2000
}

### november dashboard
GET http://localhost:8000/api/budgets/2024-11/dashboard
Authorization: Bearer {{auth}}
Content-Type: application/json
Accept: application/json

### december dashboard
GET http://localhost:8000/api/budgets/2024-12/dashboard
Authorization: Bearer {{auth}}
Content-Type: application/json
Accept: application/json

### copy previous months budget categories
POST http://localhost:8000/api/budgets/2025-02/copy-previous
Authorization: Bearer {{auth}}
Content-Type: application/json
Accept: application/json

### dashboard
DELETE http://localhost:8000/api/line-items/10
Authorization: Bearer {{auth}}
Content-Type: application/json
Accept: application/json
